Repository AndroPyro28/bulsujuans-backend, pull requests merged in 2025-10, with the labels that each got.

#1 feat: login request otp and update user & credential schema
  .env
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/auth/controllers.ts
  src/app/auth/routes.ts
  src/app/auth/schema.ts
  src/app/auth/services.ts
  src/lib/config/dotenv.ts
  src/lib/config/index.ts
  src/lib/prisma.ts
  src/lib/zod-validator.ts
  src/server.ts
Labels: enhancement

#3 feat: setup permission middleware and added initial crud endpoints for roles api
  .gitignore
  package.json
  prisma/schema.prisma
  prisma/seed.ts
  src/api.ts
  src/app/auth/controllers.ts
  src/app/auth/services.ts
  src/app/roles/controllers.ts
  src/app/roles/routes.ts
  src/app/roles/schema.ts
  src/app/roles/services.ts
  src/lib/hash-password.ts
  src/lib/jwt.ts
  src/middlewares/authenticate.ts
  src/middlewares/permission.ts
  src/types.ts
Labels: enhancement, feature

#4 feat: added new permission middleware and fix type in seeder
  prisma/seed.ts
  src/app/roles/routes.ts
  src/middlewares/permission.ts
Labels: enhancement, fix

#2 feat: request otp and verify login, email sending using html template
  .env
  package-lock.json
  package.json
  prisma/schema.prisma
  prisma/seed.ts
  public/email-templates/request-otp.html
  src/api.ts
  src/app/auth/controllers.ts
  src/app/auth/schema.ts
  src/app/auth/services.ts
  src/app/roles/routes.ts
  src/lib/config/index.ts
  src/lib/jwt.ts
  src/lib/utils.ts
  src/middlewares/error-handler.ts
  src/middlewares/permission.ts
Labels: enhancement, feature
